# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 8 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
pygments: true

title: MrBackKom
description: MrBackKom's home
author:
  name: MrBackKom
  email: zhaolong324@163.com
  github: MrBackKom

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH: http://mrbackkom.github.io
production_url : http://www.mrbackkom.com
#BASE_PATH: http://localhost:4000

# All links will be namespaced by BASE_PATH if defined.
# Links in your website should always be prefixed with {{ site.BASE_PATH }}
# Do not put a "/" at the end of the url.
#
# CNAME (http://yourcustomdomain.com)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK 
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Pages (http://username.github.io)
#   DO NOT SET BASE_PATH JUST LEAVE IT BLANK 
#   (urls will be prefixed with "/" and work relatively)
#
# GitHub Project Pages (http://username.github.io/project-name)
#  A GitHub Project site exists in the `gh-pages` branch of one of your repositories.
#  REQUIRED! Set BASE_PATH to "http://username.github.io/project-name"
